### ISSUE TITLE
Metric parsing error

### ISSUE THREAD

**Issue by brianclemens** [datamachines/telegraf-nvidia-smi#1]
I'm getting the following error with telegraf 1.5.3-1 and nvidia-utils 390.48-1 on Arch Linux

Mar 30 21:47:11 maiko telegraf[23100]: 2018-03-30T12:47:11Z E! Error in plugin [inputs.exec]:  metric parsing error, reason: [invalid value], buffer: [nvidiasmi,uuid=GPU-ae560886-e04d-5247-ff64-9cfb85a3a9b9 gpu_name="GeForce GTX 660 Ti",gpu_compute_mode="Default",fan_speed=100,memory_total=1997,memory_used=119,memory_free=1878,pstate=0,temperature=37,utilization_gpu=[Not Supported],utilization_memory=[Not Supported],gpu_index=0], index: [218]

**Comment by themistymay** [comment]
We need to resync this code with the new SMI changes as well so thanks for point this out. I'll look into this soon. Currently on vacation without an NVIDIA laptop so no way to run SMI.

**Comment by brianclemens** [comment]
Anyone looking to report Nvidia stats though telegraf should look [here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/nvidia_smi/README.md).  Closing to clean up my issues feed.
